name: Build Go App for Release

on:
  workflow_call:
    inputs:
      tag_name:
        description: "Tag to build"
        required: true
        type: string
      sha:
        description: "Commit SHA to checkout"
        required: true
        type: string
      prerelease:
        description: "Release type - prerelease or release"
        required: true
        type: boolean
    secrets:
      TUZIK_TOKEN:
        required: true

env:
  PRELELEASE_TYPE: ${{ vars.PRERELEASE_TYPE }}
  GO_VERSION: ${{ vars.GO_VERSION }}

concurrency:
  group: build-${{ inputs.tag_name }}
  cancel-in-progress: true

jobs:
  build-release:
    name: Build Go Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at release sha
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.sha }}
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run all tests
        id: test
        shell: bash
        env:
          CGO_ENABLED: 1
        run: |
          go test -v -race -coverprofile=coverage.out ./...

      - name: Build go binary
        id: build
        shell: bash
        env:
          CGO_ENABLED: 0
        run: |
          set -euo pipefail
          
          VERSION="${{ inputs.tag_name }}"
          
          targets=(
            "linux amd64"
            "linux arm64"
          )
          
          for target in "${targets[@]}"; do
            read -r GOOS GOARCH <<<"${target}"
          
            BINARY_NAME_ARCH="${{ github.event.repository.name }}-${GOOS}-${GOARCH}"
            
            echo "==> Building ${BINARY_NAME_ARCH} (GOOS=${GOOS} GOARCH=${GOARCH}) version=${VERSION}"
            GOOS="${GOOS}" GOARCH="${GOARCH}" \
            go build -ldflags "-X github.com/magenx/tuzik/version.Version=${VERSION} -s -w" \
            -o "${BINARY_NAME_ARCH}" .
          
            if [ ! -f "${BINARY_NAME_ARCH}" ]; then
              echo "Error: Build failed. Binary not found!"
              exit 1
            fi
            echo "${GOARCH}_checksum=$(sha256sum ${BINARY_NAME_ARCH})" >> ${GITHUB_OUTPUT}
          done

      - name: Upload artifacts to GitHub Release (still draft at this point)
        id: upload-artifact
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          token: ${{ secrets.TUZIK_TOKEN }}
          tag_name: ${{ inputs.tag_name }}
          files: |
            ${{ github.event.repository.name }}-*
          draft: true
          prerelease: ${{ inputs.prerelease }}
          append_body: true
          body: |
            <details>
            <summary>Installation for <strong>Linux (amd64)</strong></summary>
            <pre><code>
            curl -fsSLO https://github.com/${{ github.repository }}/releases/download/${{ inputs.tag_name }}/${{ github.event.repository.name }}-linux-amd64
            if echo "${{ steps.build.outputs.amd64_checksum }}" | sha256sum -c; then
              echo "Verification passed"
              chmod +x ${{ github.event.repository.name }}-linux-amd64
              mv ${{ github.event.repository.name }}-linux-amd64 /usr/local/sbin/${{ github.event.repository.name }}
              ${{ github.event.repository.name }} version
            else
              echo "Verification failed"
            fi
            </code></pre>
            </details>
            <details>
            <summary>Installation for <strong>Linux (arm64)</strong></summary>
            <pre><code>
            curl -fsSLO https://github.com/${{ github.repository }}/releases/download/${{ inputs.tag_name }}/${{ github.event.repository.name }}-linux-arm64
            if echo "${{ steps.build.outputs.arm64_checksum }}" | sha256sum -c; then
              echo "Verification passed"
              chmod +x ${{ github.event.repository.name }}-linux-arm64
              mv ${{ github.event.repository.name }}-linux-arm64 /usr/local/sbin/${{ github.event.repository.name }}
              ${{ github.event.repository.name }} version
            else
              echo "Verification failed"
            fi
            </code></pre>
            </details>
